### ISSUE TITLE
IOException COSStream has been closed and cannot be read

### ISSUE THREAD

**Issue by draven72** [dotemacs/pdfboxing#35] opened 2017-06-08 09:32 UTC
Hi

I'm using the example code from the readme  to try and extract the text from the second page of a pdf, but I get the following error:

`IOException COSStream has been closed and cannot be read. Perhaps its enclosing PDDocument has been closed?  org.apache.pdfbox.cos.COSStream.checkClosed (COSStream.java:77)`

This is the code I'm running:

`(text/extract
    (nth
      (split/split-pdf :input "resources/my-file.pdf")
      1))`

**Comment by dotemacs** [comment] 2017-06-08 10:05
Hello @draven72 

thanks for filing this bug report.

I've tried to see what could be the possible issue and I ran the below with the PDF included in **test/pdfs** directory: 

```clojure
(require '[pdfboxing.text :as text])
(require '[pdfboxing.split :as split])
(-> (split/split-pdf :input "test/pdfs/multi-page.pdf")
          (nth 2)
          text/extract)
```

I get this error:

```
IOException name for 'gs' operator not found in resources: /G2  org.apache.pdfbox.contentstream.operator.state.SetGraphicsStateParameters.process (SetGraphicsStateParameters.java:54)
```

Googling for it, this is the only thing that I could find about:

http://www.javanews.org/news/apache-pdfbox-javaioioexception-name-for-gs-operator-not-found-in-resources-gs8

Which is different to what you're getting.

Is there any chance that you can reproduce your error with another PDF file?
Can you share this PDF file?

Thanks

**Comment by draven72** [comment] 2017-06-08 10:58
Hi

I've failed to be able to replicate the error with other pdfs, unfortunately the one I'm using contains confidential information belonging to a client, so I can't share it.

I can pull all the text out of it using `(text/extract "resources/my-file.pdf")` but it seems to only have an issue on the split, so I don't know if there's a formatting issue with the file. If I run the function to get the number of pages it returns the correct number, but there appears to be something weird going on. 

I'm happy for you to close this, and if I'm able to replicate it with a sample pdf, I'll let you know.

Thanks

Ben

**Comment by dotemacs** [comment] 2017-06-08 11:27
Hello @draven72 

Let's not close this issue just yet.

I understand that you can't share sensitive customer data.

The way to extract text only on particular pages was introduced with this commit: https://github.com/dotemacs/pdfboxing/commit/af09ab91c854cefcdc9d2884caa528b317e36ed0

I downloaded a large PDF file from the net: https://www.niaid.nih.gov/sites/default/files/2r44ai098567-03_garrett.pdf

And using it as before:

```clojure
(-> (split/split-pdf :input "/tmp/d.pdf")
          (nth 3)
          text/extract)
```

I can get the text out.

The error that I encountered:

```
IOException name for 'gs' operator not found in resources: /G2  org.apache.pdfbox.contentstream.operator.state.SetGraphicsStateParameters.process (SetGraphicsStateParameters.java:54)
```

comes from here:

https://github.com/apache/pdfbox/blob/6f18d7c4bef4d23a22dcf14c804d737d43908deb/pdfbox/src/main/java/org/apache/pdfbox/contentstream/operator/state/SetGraphicsStateParameters.java#L54

And the error that you've encountered, comes from:
https://github.com/apache/pdfbox/blob/6f18d7c4bef4d23a22dcf14c804d737d43908deb/pdfbox/src/main/java/org/apache/pdfbox/cos/COSStream.java

Are you absolutely sure that nothing, no other process, somehow closes the particular page that you're trying to read?

I ask this because that error would not manifest unless a given page, in the form of `PDDocument`, was closed.

**Comment by dotemacs** [comment] 2017-06-08 11:36
Another idea, just to be super sure that this issue is only related to this particular PDF file that you have, can you try the following:
```
$ cd /tmp
$ git clone git@github.com:dotemacs/pdfboxing.git
$ cd pdfboxing
```
Open the project in the REPL and then:

```clojure
(require '[pdfboxing.text :as text])
(require '[pdfboxing.split :as split])
(-> (split/split-pdf :input "your-pdf.pdf")
          (nth 2)
          text/extract)
```

Does just the above produce the same error?

Then, try the following:

```
open project.clj
upgrade pdfbox from 2.0.4 to 2.0.6
run: lein deps 
```

Then repeat the steps above, where you try to read `nth` page. Does the error manifest itself even with the latest `pdfbox` version?

Thanks

**Comment by draven72** [comment] 2017-06-08 11:51
Hi

After updgrading pdfbox, I now get  more details in the error:

`Jun 08, 2017 12:45:56 PM org.apache.pdfbox.pdmodel.font.PDFont <init>
SEVERE: Could not read ToUnicode CMap in font MUFUZY+ArialMT
java.io.IOException: COSStream has been closed and cannot be read. Perhaps its enclosing PDDocument has been closed?...`

`Jun 08, 2017 12:45:56 PM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+16 (16) in font MUFUZY+ArialMT
Jun 08, 2017 12:45:56 PM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+32 (32) in font MUFUZY+ArialMT
Jun 08, 2017 12:45:56 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 codeToGID
WARNING: Failed to find a character mapping for 32 in MUFUZY+ArialMT
Jun 08, 2017 12:45:56 PM org.apache.pdfbox.pdmodel.font.PDFont <init>
SEVERE: Could not read ToUnicode CMap in font MUFUZY+Arial-BoldMT
...`

Looks like the issue is with the font?

**Comment by dotemacs** [comment] 2017-06-08 12:03
From the message above, that's exactly what it looks like.

Can you try to create a sample PDF using the same software/process that produced the one that the error is manifesting on, but use some regular font and see if the error persists?

If it doesn't error, then the font is the culprit. Or better, PDFbox can't handle that particular font.

Let me know how you get on.

**Comment by draven72** [comment] 2017-06-08 12:31
Unfortunately the pdf is created by a third party who emails it to the client, so I'm able to create it exactly, but according to the info it was created using Google Sheets, so I'll try and see if I can export a pdf from Google docs and test that

**Comment by dotemacs** [comment] 2017-06-20 17:38
Hi @draven72 

has there been any other progress on this or shall I close the issue?

Thank for your time

**Comment by dotemacs** [comment] 2017-06-23 08:17
@draven72 I've released the new version of pdfboxing which pulls in the latest stable PDFBox:

https://clojars.org/pdfboxing/versions/0.1.13

What shall I do about this issue? 

Thanks

**Comment by draven72** [comment] 2017-06-23 09:48
@dotemacs I still haven't been able to reproduce the error myself, and as the file comes from a third party that sends it to our client, I don't think I'll get much help from them. 

I'm happy for this ticket to be closed, I'm able to parse the file, I just can't split it, which isn't critical.

**Comment by dotemacs** [comment] 2017-06-23 09:53
Thanks @draven72

**Closed by dotemacs** 2017-06-23 09:53 UTC
Labels: bug
